#This play book performs the following:
#  - YUM: https://docs.ansible.com/ansible/2.9/modules/yum_module.html
#  - FDISK: Created partitions: https://docs.ansible.com/ansible/2.9/modules/parted_module.html
#  - VGCREATE: Create physical volumes and volume groups: https://docs.ansible.com/ansible/2.9/modules/lvg_module.html
#  - LVCREATE: https://docs.ansible.com/ansible/2.9/modules/lvol_module.html
#  - MKFS.XFS: https://docs.ansible.com/ansible/2.9/modules/filesystem_module.html
#  - MKDIR and CHMOD a+rwx: https://docs.ansible.com/ansible/2.9/modules/file_module.html

- name: Configure NFS server
  hosts: nfs
  become: yes
  gather_facts: yes

  tasks:

  - name: Install required packages #https://docs.ansible.com/ansible/2.9/modules/yum_module.html
    yum:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - lvm2
      - nfs-utils
      - libnfsidmap
      - firewalld
      - git


#  - FDISK: Created partitions: https://docs.ansible.com/ansible/2.9/modules/parted_module.html
  - name: Create a new primary partition for LVM in /dev/xvdb
    parted:
        device: /dev/xvdb
        number: 1
        flags: [ lvm ]
        state: present


  - name: Create a new primary partition for LVM in /dev/xvdc
    parted:
        device: /dev/xvdc
        number: 1
        flags: [ lvm ]
        state: present


  - name: Create a new primary partition for LVM in /dev/xvdd
    parted:
        device: /dev/xvdd
        number: 1
        flags: [ lvm ]
        state: present


#  - VGCREATE: Create physical volumes and volume groups: https://docs.ansible.com/ansible/2.9/modules/lvg_module.html
  - name: VGCREATE to Create or resize a volume group on top of /dev/xvdb1,/dev/xvdc1,/dev/xvdd1
    lvg:
        vg: nfs_vg
        pvs: /dev/xvdb1,/dev/xvdc1,/dev/xvdd1


#  - LVCREATE: https://docs.ansible.com/ansible/2.9/modules/lvol_module.html
  - name: Create a logical volume lv-opt of 5GiB
    lvol:
      vg: nfs_vg
      lv: lv-opt
      size: 5g

  - name: Create a logical volume lv-apps of 5GiB
    lvol:
      vg: nfs_vg
      lv: lv-apps
      size: 5g


  - name: Create a logical volume lv-logs of 5GiB
    lvol:
      vg: nfs_vg
      lv: lv-logs
      size: 4.9g

#Use mkfs.xfs to format the logical volume with Xfs filesystem
#  - MKFS.XFS: https://docs.ansible.com/ansible/2.9/modules/filesystem_module.html
  - name: Create a xfs filesystem on /dev/nfs_vg/lv-opt
    filesystem:
      fstype: xfs
      dev: /dev/nfs_vg/lv-opt

  - name: Create a xfs filesystem on /dev/nfs_vg/lv-apps
    filesystem:
      fstype: xfs
      dev: /dev/nfs_vg/lv-apps

  - name: Create a xfs filesystem on /dev/nfs_vg/lv-logs
    filesystem:
      fstype: xfs
      dev: /dev/nfs_vg/lv-logs


#  - MKDIR and CHMOD a+rwx: https://docs.ansible.com/ansible/2.9/modules/file_module.html
  - name: Make directory /mnt/html
    file:
      path: /mnt/html
      state: directory
      mode: '0777'

  - name: Make directory /mnt/logs
    file:
      path: /mnt/logs
      state: directory
      mode: '0777'

  - name: Make directory /mnt/opt
    file:
      path: /mnt/opt
      state: directory
      mode: '0777'


#  - MOUNT DIRECTORIES TO LOGICAL VOLUMES: https://docs.ansible.com/ansible/2.9/modules/mount_module.html
  - name: Mount /mnt/html to /dev/nfs_vg/lv-apps
    mount:
      path: /mnt/html
      src: /dev/nfs_vg/lv-apps
      fstype: xfs
      state: mounted

  - name: Mount /mnt/html to /dev/nfs_vg/lv-opt
    mount:
      path: /mnt/opt
      src: /dev/nfs_vg/lv-opt
      fstype: xfs
      state: mounted


  - name: Mount /mnt/html to /dev/nfs_vg/lv-logs
    mount:
      path: /mnt/logs
      src: /dev/nfs_vg/lv-logs
      fstype: xfs
      state: mounted
